federatedGateway:
  enabled: true
federated-gateway:  
  gatewayURL: 'http://gateway.openfaas:8080'
  issuer: https://kubiya-dev.us.auth0.com/
  audience: kubiya-ai-tunnel-dev-eks-runner.kubiya-ai
  allowInvoke: 'true'
  logs:
    debug: 'true'
    format: 'json'
openfaas:
  enabled: true
