federatedGateway:
  enabled: true
federated-gateway:  
  gatewayURL: 'http://gateway.openfaas:8080'
  issuer: https://kubiya-dev.us.auth0.com/
  audience: kubiya-ai-tunnel-dev-eks-runner.kubiya-ai
  allowInvoke: 'true'
  logs:
    debug: 'true'
    format: 'json'
openfaas:
  enabled: true
  functions:
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10

foo: bar