apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fnasd
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "4222"
    config.linkerd.io/skip-outbound-ports: "4222"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
  labels:
    istio-injection: enabled
    role: openfaas-fn